groups:
  - name: raspberrypi-alerts
    rules:

      - alert: HighCPUUsage
        expr: pi_cpu_usage_percent > 80
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is above 80% for more than 2 minutes."

      - alert: HighDiskUsage
        expr: pi_disk_usage_percent > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High disk usage detected"
          description: "Disk usage is above 85%."

      - alert: HighTemperature
        expr: pi_temperature_celsius > 70
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "High Raspberry Pi temperature"
          description: "Pi temperature is above 70°C."

  - name: pihole-alerts
    rules:

      - alert: PiHoleDown
        expr: up{job="pihole"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Pi-hole exporter down"
          description: "Prometheus cannot scrape the Pi-hole exporter."

      - alert: NoActiveClients
        expr: sum(pihole_client_count{category="active"}) == 0
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "No active Pi-hole clients"
          description: "No devices are actively using Pi-hole."

      - alert: HighBlockedQueryPercentage
        expr: (100 * sum(pihole_query_count{category="blocked"}) / sum(pihole_query_count{category="total"})) > 75
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High blocked query percentage"
          description: "Blocked DNS percentage exceeded 40%."

