global:
  scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: "pimonitor"
    static_configs:
      - targets: ["pimonitor:5000"]

  - job_name: "pihole"
    static_configs:
      - targets: ["pihole-exporter:9666"]
